'use strict';

module.exports = {
  /**
   * An asynchronous register function that runs before
   * your application is initialized.
   *
   * This gives you an opportunity to extend code.
   */
    register() {},

  /**
   * An asynchronous bootstrap function that runs before
   * your application gets started.
   *
   * This gives you an opportunity to set up your data model,
   * run jobs, or perform some special logic.
   */
  bootstrap() {
    const data = ["Lavazza Coffee",
    "Espresso",
    "Espresso con Panna",
    "Espresso Macchiato",
    "Latte Macchiato",
    "Cappuccino",
    "Mocha",
    "Caffe Au Lait",
    "Flat White",
    "Caffe Americano",
    "Hot Chocolate",
    "Cortado",
    "Steamed Milk",
    "Caffe Latte",
    "Matcha Latte",
    "Chai Tea Latte",
    "Matcha Tea",
    "Hot Tea",
    "Iced Coffee",
    "Iced Cappuccino",
    "Iced Mocha",
    "Iced Americano",
    "Iced Chai Latte",
    "Iced Latte",
    "Italian Frappe Coffee",
    "Italian Chocolate Frappe",
    "Italian Mocha Frappe",
    "Italian Strawberry Frappe",
    "Iced Tea",
    "Iced Matcha Latte",
    "Ice-Ice Baby",
    "Marshmallow Mocca",
    "Babyccino",
    "All Dogs go to Heaven",
    "Sweet Potato",
    "Cold Brew",
    "Cold Amaretto",
    "Passion Me Cold Brew",
    "Black Cherry Cold Brew",
    "Nutty Nitro",
    "Coco Choc Nitro",
    "Melonate ",
    "Pina Coco-Lada",
    "Berry Burst Fusion",
    "Mango Dreamsicle",
    "Apple Citrus",
    "Tropical Boba Tea",
    "White Banana Boba Tea",
    "Macchiato Boba Tea",
    "Berry Boba Tea",
    "Jasmine Boba Tea",
    "Honey Matcha Boba Tea",
    "Mother of Dragons",
    "Watermelon Cooler",
    "Galaxy ",
    "Blue Lagoon",
    "Mango Colada",
    "Green Caramel Apple",
    "Creamsicle",
    "Strawberries & Cream",
    "S'mores Mocha (hot)",
    "S'mores Mocha (frappe)",
    "S'mores Mocha (iced)",
    "Passion-ade Frappe",
    "Citrus Twist Cold Brew",
    "Citrus Twist Soda",
    "Holiday Mocha",
    "Holiday Mocha Frappe",
    "Hazel-ccino",
    "Hazel-ccino Frappe",
    "Red Nose Cold Brew",
    "Grinch-mas Matcha",
    "Lavender Mocha Frappe",
    "Lavender Mocha",
    "Water-mello Cold Brew",
    "Bubbly Spring Breeze/ Bubbly Spring Soda",
    "Sunny Smoothie Frappe",
    "Hawaiian Soda",
    "Hawaiian Cold Brew",
    "Citrus Orange Mocha",
    "Citrus Orange Mocha Frappe",
    "Sweet Maple Tree Latte",
    "Sweet Maple Tree Latte Frappe",
    "Iced Pumpkin Au Lait",
    "Pumpkin Au Lait",
    "Pumpkin Cold Brew",
    "Fall Italian Frappe",
    "Acai",
    "Pina Colada Acai",
    "Mango Acai",
    "Chocolate Croissant All Butter",
    "Plain All Butter Croissant",
    "Vegan Croissant Vuoto",
    "Cornetto Glazed Apricot",
    "Cornetto Glazed Pistachio",
    "Cornetto Alla Crema",
    "Cornetto Vuoto",
    "Vanilla Eclair",
    "Chocolate Eclair",
    "Coffee Eclair",
    "Black currant Eclair",
    "Mango Passion Fruit Eclair ",
    "Raspberry Eclair",
    "Cappuccino Cake",
    "Chocolate Temptation Cake",
    "Red Velvet Cake",
    "Carrot Cake",
    "Tiramisu Individual",
    "Mixed Berry Tart",
    "Napoleon (Millefoglie)",
    "Cheesecake Pistachio",
    "Dulce De Leche Cheesecake",
    "Cheesecake Brulee",
    "Limoncello Mascarpone Cake",
    "Chocolate Fondant Cake ",
    "Tres Leches Cake",
    "Sicilian Cannoli",
    "Chocolate Caramel Crunch GF",
    "Pyramid",
    "Torta Nocciola ",
    "Chocolate Ganache Cheesecake ",
    "Chocolate Ganache Tartlet - Vegan",
    "Cheesecake Alle Fragole (Strawberry Cheesecake)",
    "Bomboloni Cream",
    "Bomboloni Cacao Nocciola",
    "Mini Bomboloni Cacao Nocciola",
    "Macarons French Collection",
    "Pastiera Monoporzione ",
    "Mini croissant",
    "Cantucci",
    "Coconut Ripieno",
    "Orange Ripieno",
    "Lemon Ripieno",
    "Pineapple Ripieno",
    "Coppa Caffe ",
    "Coppa Pistacho ",
    "Coppa Spagnola ",
    "Coppa Mascarpone",
    "Mango Guava Flute ",
    "Double Chocolate Muffin",
    "Blueberry Muffin",
    "Original Bran Muffin",
    "Banana Nut Muffin",
    "Cappuccino Muffin",
    "Orange Cranberry Muffin",
    "Double Chocolate w/ Cream Cheese Mini Muffin",
    "Lemon w/ Raspberry Mini Muffin",
    "Banana w/ Nutella Mini Muffin",
    "Pumpkin w/ Cream Cheese Mini Muffin",
    "Cinnamon Raisin Bagel",
    "Everything Bagel",
    "Onion Bagel",
    "Plain Bagel",
    "Sesame Bagel",
    "Jalapeno Cheddar Bagel",
    "Chocolate Chunk Scone",
    "Blueberry Scone",
    "Mixed Berry Scone",
    "Pumpkin Triangle Baked Scone",
    "Cinnamon Roll",
    "Bear Claw",
    "Cheese Danish Twist",
    "Cherry Filling Danish Twist",
    "Danish, Lemon & Blueberry",
    "Apple Filling Danish Twist",
    "Iced Pumpkin Tea Bread",
    "Marble Tea Bread",
    "Blueberry Tea Bread",
    "Vegan Banana Nut Tea Bread",
    "Lemon with Icing Pound Cake",
    "Spinach, Kale & Cheese Croissant",
    "Blueberry Peach Parfait",
    "Strawberry Banana Parfait",
    "Strawberry Blueberry Parfait",
    "Blueberry Overnight Oats",
    "Prosciutto & Mozz Croissant",
    "Turkey Bacon, Egg, and Cheddar Olive Ciabatta",
    "Veggie Capressee Ciabatta",
    "Turkey Sausage, Egg, and Cheddar Pretzel Croissant",
    "Turkey Bac, Egg, and Cheddar Jalapeno Cheese Bagel",
    "Sausage, Egg, and Cheddar Everything Bagel",
    "Il Classico",
    "Pioggia di Prosciutto ",
    "Super Italiano ",
    "Falafel Magic ",
    "Tzatziki Chicken",
    "Double-B TA",
    "Belgian Waffle",
    "Mini Dutch Pancakes",
    "San Pellegrino Sparkling Mineral pet Water 500ml",
    "San Pellegrino Aranciata Rossa",
    "San Pellegrino Aranciata (Orange)",
    "San Pellegrino Limonata",
    "Revolution Tea Lemon Sparkling Tea",
    "Revolution Tea Green Apple Sparkling Tea ",
    "Revolution Tea Black Currant Blueberry Sparkling Tea",
    "Revolution Tea Passion Fruit Sparkling Tea ",
    "Acqua Panna Still Water pet 500ml",
    "Red Wine Dealcoholized ",
    "Cali Red Wine Dealcoholized ",
    "Vermouth Dealcoholized ",
    "Rose Champagne Dealcoholized ",]

    
    data.forEach(async (item)  => {
      
      const entry = await strapi.entityService.create('api::coffee.coffee', {
        data: {
          title: item,
          slug: item.toLowerCase().replace(/\s+/g, '-').replace(/[^\w\-]+/g, '')
        },
      });

    });
  },
};
